// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client2server.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	client2server.proto

It has these top-level messages:
	LoginRequest
	LoginResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 首次登陆，客户端启动时请求
type LoginRequest struct {
	DeviceId         *string `protobuf:"bytes,1,req,name=deviceId" json:"deviceId,omitempty"`
	ThirdAccountType *int32  `protobuf:"varint,3,req,name=thirdAccountType" json:"thirdAccountType,omitempty"`
	ThirdAccount     *string `protobuf:"bytes,4,req,name=thirdAccount" json:"thirdAccount,omitempty"`
	ThirdPasswd      *string `protobuf:"bytes,5,req,name=thirdPasswd" json:"thirdPasswd,omitempty"`
	PfType           *int32  `protobuf:"varint,6,req,name=pfType" json:"pfType,omitempty"`
	Version          *string `protobuf:"bytes,7,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *LoginRequest) GetThirdAccountType() int32 {
	if m != nil && m.ThirdAccountType != nil {
		return *m.ThirdAccountType
	}
	return 0
}

func (m *LoginRequest) GetThirdAccount() string {
	if m != nil && m.ThirdAccount != nil {
		return *m.ThirdAccount
	}
	return ""
}

func (m *LoginRequest) GetThirdPasswd() string {
	if m != nil && m.ThirdPasswd != nil {
		return *m.ThirdPasswd
	}
	return ""
}

func (m *LoginRequest) GetPfType() int32 {
	if m != nil && m.PfType != nil {
		return *m.PfType
	}
	return 0
}

func (m *LoginRequest) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type LoginResponse struct {
	ErrorCode        *int32  `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	Ip               *string `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	Port             *int32  `protobuf:"varint,3,req,name=port" json:"port,omitempty"`
	AuthCode         *string `protobuf:"bytes,4,req,name=authCode" json:"authCode,omitempty"`
	AccountId        *int64  `protobuf:"varint,5,req,name=accountId" json:"accountId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResponse) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *LoginResponse) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *LoginResponse) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *LoginResponse) GetAuthCode() string {
	if m != nil && m.AuthCode != nil {
		return *m.AuthCode
	}
	return ""
}

func (m *LoginResponse) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "pb.loginRequest")
	proto.RegisterType((*LoginResponse)(nil), "pb.loginResponse")
}

func init() { proto.RegisterFile("client2server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xce, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x06, 0x60, 0xd5, 0x6d, 0xda, 0xe6, 0x08, 0x90, 0xba, 0x0c, 0x1e, 0xab, 0x4e, 0x9d, 0x18,
	0x78, 0x03, 0xc4, 0x94, 0x0d, 0x21, 0x5e, 0xc0, 0xd8, 0x07, 0xb1, 0x14, 0xf9, 0xcc, 0xd9, 0x09,
	0xe2, 0x05, 0x78, 0x6e, 0xc4, 0x25, 0x03, 0xeb, 0x7f, 0xff, 0x7f, 0xfa, 0xe0, 0xe8, 0x86, 0x80,
	0xb1, 0x3c, 0x64, 0xe4, 0x09, 0xf9, 0x3e, 0x31, 0x15, 0xd2, 0x2a, 0xbd, 0x9d, 0x7f, 0x56, 0xd0,
	0x0c, 0xf4, 0x11, 0xe2, 0x0b, 0x7e, 0x8e, 0x98, 0x8b, 0x6e, 0x61, 0xef, 0x71, 0x0a, 0x0e, 0x3b,
	0x6f, 0x56, 0x27, 0x75, 0xa9, 0xb5, 0x81, 0xb6, 0xf4, 0x81, 0xfd, 0xa3, 0x73, 0x34, 0xc6, 0xf2,
	0xfa, 0x9d, 0xd0, 0xac, 0x4f, 0xea, 0x52, 0xe9, 0x3b, 0x68, 0xfe, 0x5f, 0xcc, 0x46, 0xfa, 0x47,
	0xb8, 0x92, 0xf4, 0xd9, 0xe6, 0xfc, 0xe5, 0x4d, 0x25, 0xe1, 0x0d, 0x6c, 0xd3, 0xbb, 0x4c, 0xb7,
	0x32, 0xbd, 0x85, 0xdd, 0x84, 0x9c, 0x03, 0x45, 0xb3, 0xfb, 0x2b, 0x9c, 0x2d, 0x5c, 0x2f, 0x8e,
	0x9c, 0x28, 0x66, 0xd4, 0x07, 0xa8, 0x91, 0x99, 0xf8, 0x89, 0x3c, 0x8a, 0xa4, 0xd2, 0x00, 0x2a,
	0x24, 0xa3, 0xe4, 0x61, 0x03, 0x9b, 0x44, 0x5c, 0x16, 0x49, 0x0b, 0x7b, 0x3b, 0x96, 0x5e, 0xba,
	0xb3, 0xe2, 0x00, 0xb5, 0x9d, 0x59, 0xdd, 0x6c, 0x58, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x0e,
	0xf3, 0x0d, 0x31, 0x05, 0x01, 0x00, 0x00,
}
