// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client2server.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	client2server.proto

It has these top-level messages:
	LoginRequest
	LoginResponse
	GameServerLoginRequest
	GameServerLoginResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 首次登陆，客户端启动时请求
type LoginRequest struct {
	DeviceId         *string `protobuf:"bytes,1,req,name=deviceId" json:"deviceId,omitempty"`
	ThirdAccountType *int32  `protobuf:"varint,3,req,name=thirdAccountType" json:"thirdAccountType,omitempty"`
	ThirdAccount     *string `protobuf:"bytes,4,req,name=thirdAccount" json:"thirdAccount,omitempty"`
	ThirdPasswd      *string `protobuf:"bytes,5,req,name=thirdPasswd" json:"thirdPasswd,omitempty"`
	PfType           *int32  `protobuf:"varint,6,req,name=pfType" json:"pfType,omitempty"`
	Version          *string `protobuf:"bytes,7,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *LoginRequest) GetThirdAccountType() int32 {
	if m != nil && m.ThirdAccountType != nil {
		return *m.ThirdAccountType
	}
	return 0
}

func (m *LoginRequest) GetThirdAccount() string {
	if m != nil && m.ThirdAccount != nil {
		return *m.ThirdAccount
	}
	return ""
}

func (m *LoginRequest) GetThirdPasswd() string {
	if m != nil && m.ThirdPasswd != nil {
		return *m.ThirdPasswd
	}
	return ""
}

func (m *LoginRequest) GetPfType() int32 {
	if m != nil && m.PfType != nil {
		return *m.PfType
	}
	return 0
}

func (m *LoginRequest) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type LoginResponse struct {
	ErrorCode        *int32  `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	Ip               *string `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	Port             *int32  `protobuf:"varint,3,req,name=port" json:"port,omitempty"`
	AuthCode         *string `protobuf:"bytes,4,req,name=authCode" json:"authCode,omitempty"`
	AccountId        *int64  `protobuf:"varint,5,req,name=accountId" json:"accountId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResponse) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *LoginResponse) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *LoginResponse) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *LoginResponse) GetAuthCode() string {
	if m != nil && m.AuthCode != nil {
		return *m.AuthCode
	}
	return ""
}

func (m *LoginResponse) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

// 登陆游戏服务器
type GameServerLoginRequest struct {
	AccountId        *int64  `protobuf:"varint,1,req,name=accountId" json:"accountId,omitempty"`
	AuthCode         *string `protobuf:"bytes,2,req,name=authCode" json:"authCode,omitempty"`
	PfType           *int32  `protobuf:"varint,3,req,name=pfType" json:"pfType,omitempty"`
	Version          *string `protobuf:"bytes,4,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GameServerLoginRequest) Reset()                    { *m = GameServerLoginRequest{} }
func (m *GameServerLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*GameServerLoginRequest) ProtoMessage()               {}
func (*GameServerLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GameServerLoginRequest) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *GameServerLoginRequest) GetAuthCode() string {
	if m != nil && m.AuthCode != nil {
		return *m.AuthCode
	}
	return ""
}

func (m *GameServerLoginRequest) GetPfType() int32 {
	if m != nil && m.PfType != nil {
		return *m.PfType
	}
	return 0
}

func (m *GameServerLoginRequest) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type GameServerLoginResponse struct {
	ErrorCode        *int32 `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GameServerLoginResponse) Reset()                    { *m = GameServerLoginResponse{} }
func (m *GameServerLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*GameServerLoginResponse) ProtoMessage()               {}
func (*GameServerLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GameServerLoginResponse) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "pb.loginRequest")
	proto.RegisterType((*LoginResponse)(nil), "pb.loginResponse")
	proto.RegisterType((*GameServerLoginRequest)(nil), "pb.gameServerLoginRequest")
	proto.RegisterType((*GameServerLoginResponse)(nil), "pb.gameServerLoginResponse")
}

func init() { proto.RegisterFile("client2server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x55, 0xa7, 0x69, 0x9b, 0x23, 0x40, 0xea, 0x22, 0xf0, 0x58, 0x65, 0xea, 0x80, 0x18,
	0x78, 0x03, 0xc4, 0x54, 0x89, 0x01, 0x01, 0x33, 0x92, 0x89, 0x8f, 0xd6, 0x52, 0xb1, 0xcd, 0xd9,
	0x09, 0xe2, 0x05, 0x78, 0x6e, 0xd4, 0x4b, 0x87, 0xb6, 0x88, 0xf5, 0xfc, 0xdf, 0x7f, 0xdf, 0x67,
	0x98, 0x35, 0x1b, 0x8b, 0x2e, 0xdd, 0x46, 0xa4, 0x0e, 0xe9, 0x26, 0x90, 0x4f, 0x5e, 0x8a, 0xf0,
	0x56, 0xff, 0x0c, 0xa0, 0xdc, 0xf8, 0x95, 0x75, 0x4f, 0xf8, 0xd9, 0x62, 0x4c, 0xb2, 0x82, 0x89,
	0xc1, 0xce, 0x36, 0xb8, 0x34, 0x6a, 0x30, 0x17, 0x8b, 0x42, 0x2a, 0xa8, 0xd2, 0xda, 0x92, 0xb9,
	0x6b, 0x1a, 0xdf, 0xba, 0xf4, 0xf2, 0x1d, 0x50, 0x65, 0x73, 0xb1, 0xc8, 0xe5, 0x05, 0x94, 0xfb,
	0x2f, 0x6a, 0xc8, 0xf9, 0x19, 0x9c, 0xf0, 0xf4, 0x51, 0xc7, 0xf8, 0x65, 0x54, 0xce, 0xc3, 0x33,
	0x18, 0x85, 0x77, 0x5e, 0x1d, 0xf1, 0xea, 0x39, 0x8c, 0x3b, 0xa4, 0x68, 0xbd, 0x53, 0xe3, 0x6d,
	0xa0, 0xd6, 0x70, 0xba, 0xe3, 0x88, 0xc1, 0xbb, 0x88, 0x72, 0x0a, 0x05, 0x12, 0x79, 0xba, 0xf7,
	0x06, 0x99, 0x24, 0x97, 0x00, 0xc2, 0x06, 0x25, 0xb8, 0xb0, 0x84, 0x61, 0xf0, 0x94, 0x76, 0x24,
	0x15, 0x4c, 0x74, 0x9b, 0xd6, 0x9c, 0xed, 0x29, 0xa6, 0x50, 0xe8, 0x1e, 0x6b, 0xd9, 0x33, 0x64,
	0xf5, 0x2b, 0x5c, 0xae, 0xf4, 0x07, 0x3e, 0xf3, 0x1f, 0x3c, 0xec, 0x4b, 0x1f, 0x84, 0xb7, 0xb7,
	0xb2, 0x83, 0x46, 0x71, 0xa4, 0x90, 0x1d, 0x2b, 0xf0, 0xc9, 0xfa, 0x1a, 0xae, 0xfe, 0xf4, 0xff,
	0x2b, 0xf3, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x65, 0x14, 0xc5, 0xf0, 0x93, 0x01, 0x00, 0x00,
}
