// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client2server.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	client2server.proto

It has these top-level messages:
	LoginRequest
	LoginResponse
	GameServerLoginRequest
	GameServerLoginResponse
	SyncBaseInfoRequest
	SyncBaseInfoResponse
	PingRequest
	PingResponse
	GetFriendListForStrengthRequesst
	GetFriendListForStrengthResponse
	SendGameResumeRequest
	SendGameResumeResponse
	LogGameResume
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 首次登陆，客户端启动时请求
type LoginRequest struct {
	DeviceId         *string `protobuf:"bytes,1,req,name=deviceId" json:"deviceId,omitempty"`
	ThirdAccountType *int32  `protobuf:"varint,3,req,name=thirdAccountType" json:"thirdAccountType,omitempty"`
	ThirdAccount     *string `protobuf:"bytes,4,req,name=thirdAccount" json:"thirdAccount,omitempty"`
	ThirdPasswd      *string `protobuf:"bytes,5,req,name=thirdPasswd" json:"thirdPasswd,omitempty"`
	PfType           *int32  `protobuf:"varint,6,req,name=pfType" json:"pfType,omitempty"`
	Version          *string `protobuf:"bytes,7,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *LoginRequest) GetThirdAccountType() int32 {
	if m != nil && m.ThirdAccountType != nil {
		return *m.ThirdAccountType
	}
	return 0
}

func (m *LoginRequest) GetThirdAccount() string {
	if m != nil && m.ThirdAccount != nil {
		return *m.ThirdAccount
	}
	return ""
}

func (m *LoginRequest) GetThirdPasswd() string {
	if m != nil && m.ThirdPasswd != nil {
		return *m.ThirdPasswd
	}
	return ""
}

func (m *LoginRequest) GetPfType() int32 {
	if m != nil && m.PfType != nil {
		return *m.PfType
	}
	return 0
}

func (m *LoginRequest) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type LoginResponse struct {
	ErrorCode        *int32  `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	Ip               *string `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	Port             *int32  `protobuf:"varint,3,req,name=port" json:"port,omitempty"`
	AuthCode         *string `protobuf:"bytes,4,req,name=authCode" json:"authCode,omitempty"`
	AccountId        *int64  `protobuf:"varint,5,req,name=accountId" json:"accountId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResponse) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *LoginResponse) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *LoginResponse) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *LoginResponse) GetAuthCode() string {
	if m != nil && m.AuthCode != nil {
		return *m.AuthCode
	}
	return ""
}

func (m *LoginResponse) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

// 登陆游戏服务器
type GameServerLoginRequest struct {
	AccountId        *int64  `protobuf:"varint,1,req,name=accountId" json:"accountId,omitempty"`
	AuthCode         *string `protobuf:"bytes,2,req,name=authCode" json:"authCode,omitempty"`
	PfType           *int32  `protobuf:"varint,3,req,name=pfType" json:"pfType,omitempty"`
	Version          *string `protobuf:"bytes,4,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GameServerLoginRequest) Reset()                    { *m = GameServerLoginRequest{} }
func (m *GameServerLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*GameServerLoginRequest) ProtoMessage()               {}
func (*GameServerLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GameServerLoginRequest) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *GameServerLoginRequest) GetAuthCode() string {
	if m != nil && m.AuthCode != nil {
		return *m.AuthCode
	}
	return ""
}

func (m *GameServerLoginRequest) GetPfType() int32 {
	if m != nil && m.PfType != nil {
		return *m.PfType
	}
	return 0
}

func (m *GameServerLoginRequest) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type GameServerLoginResponse struct {
	ErrorCode        *int32 `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GameServerLoginResponse) Reset()                    { *m = GameServerLoginResponse{} }
func (m *GameServerLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*GameServerLoginResponse) ProtoMessage()               {}
func (*GameServerLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GameServerLoginResponse) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

// 名字和头像同步
type SyncBaseInfoRequest struct {
	HeadImage        *int32  `protobuf:"varint,1,req,name=headImage" json:"headImage,omitempty"`
	Nickname         *string `protobuf:"bytes,2,req,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SyncBaseInfoRequest) Reset()                    { *m = SyncBaseInfoRequest{} }
func (m *SyncBaseInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncBaseInfoRequest) ProtoMessage()               {}
func (*SyncBaseInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SyncBaseInfoRequest) GetHeadImage() int32 {
	if m != nil && m.HeadImage != nil {
		return *m.HeadImage
	}
	return 0
}

func (m *SyncBaseInfoRequest) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

type SyncBaseInfoResponse struct {
	ErrorCode        *int32 `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SyncBaseInfoResponse) Reset()                    { *m = SyncBaseInfoResponse{} }
func (m *SyncBaseInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*SyncBaseInfoResponse) ProtoMessage()               {}
func (*SyncBaseInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SyncBaseInfoResponse) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

type PingRequest struct {
	ClientTime       *int32 `protobuf:"varint,1,req,name=clientTime" json:"clientTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PingRequest) GetClientTime() int32 {
	if m != nil && m.ClientTime != nil {
		return *m.ClientTime
	}
	return 0
}

type PingResponse struct {
	ErrorCode        *int32 `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	ClientTime       *int32 `protobuf:"varint,2,req,name=clientTime" json:"clientTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PingResponse) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *PingResponse) GetClientTime() int32 {
	if m != nil && m.ClientTime != nil {
		return *m.ClientTime
	}
	return 0
}

// 获取请求体力的好友名单
type GetFriendListForStrengthRequesst struct {
	Placeholder      *int32 `protobuf:"varint,1,req,name=placeholder" json:"placeholder,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetFriendListForStrengthRequesst) Reset()         { *m = GetFriendListForStrengthRequesst{} }
func (m *GetFriendListForStrengthRequesst) String() string { return proto.CompactTextString(m) }
func (*GetFriendListForStrengthRequesst) ProtoMessage()    {}
func (*GetFriendListForStrengthRequesst) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8}
}

func (m *GetFriendListForStrengthRequesst) GetPlaceholder() int32 {
	if m != nil && m.Placeholder != nil {
		return *m.Placeholder
	}
	return 0
}

type GetFriendListForStrengthResponse struct {
	ErrorCode        *int32   `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	AccountIds       []uint64 `protobuf:"varint,2,rep,name=accountIds" json:"accountIds,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetFriendListForStrengthResponse) Reset()         { *m = GetFriendListForStrengthResponse{} }
func (m *GetFriendListForStrengthResponse) String() string { return proto.CompactTextString(m) }
func (*GetFriendListForStrengthResponse) ProtoMessage()    {}
func (*GetFriendListForStrengthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9}
}

func (m *GetFriendListForStrengthResponse) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *GetFriendListForStrengthResponse) GetAccountIds() []uint64 {
	if m != nil {
		return m.AccountIds
	}
	return nil
}

type SendGameResumeRequest struct {
	Data             *LogGameResume `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SendGameResumeRequest) Reset()                    { *m = SendGameResumeRequest{} }
func (m *SendGameResumeRequest) String() string            { return proto.CompactTextString(m) }
func (*SendGameResumeRequest) ProtoMessage()               {}
func (*SendGameResumeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SendGameResumeRequest) GetData() *LogGameResume {
	if m != nil {
		return m.Data
	}
	return nil
}

type SendGameResumeResponse struct {
	ErrorCode        *int32 `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SendGameResumeResponse) Reset()                    { *m = SendGameResumeResponse{} }
func (m *SendGameResumeResponse) String() string            { return proto.CompactTextString(m) }
func (*SendGameResumeResponse) ProtoMessage()               {}
func (*SendGameResumeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SendGameResumeResponse) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

type LogGameResume struct {
	Logtime          *int32  `protobuf:"varint,2,req,name=logtime" json:"logtime,omitempty"`
	RuntimeVersion   *string `protobuf:"bytes,3,req,name=runtimeVersion" json:"runtimeVersion,omitempty"`
	NetworkType      *string `protobuf:"bytes,4,req,name=networkType" json:"networkType,omitempty"`
	DeviceModel      *string `protobuf:"bytes,5,req,name=deviceModel" json:"deviceModel,omitempty"`
	AndroidSdk       *int32  `protobuf:"varint,6,req,name=androidSdk" json:"androidSdk,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LogGameResume) Reset()                    { *m = LogGameResume{} }
func (m *LogGameResume) String() string            { return proto.CompactTextString(m) }
func (*LogGameResume) ProtoMessage()               {}
func (*LogGameResume) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *LogGameResume) GetLogtime() int32 {
	if m != nil && m.Logtime != nil {
		return *m.Logtime
	}
	return 0
}

func (m *LogGameResume) GetRuntimeVersion() string {
	if m != nil && m.RuntimeVersion != nil {
		return *m.RuntimeVersion
	}
	return ""
}

func (m *LogGameResume) GetNetworkType() string {
	if m != nil && m.NetworkType != nil {
		return *m.NetworkType
	}
	return ""
}

func (m *LogGameResume) GetDeviceModel() string {
	if m != nil && m.DeviceModel != nil {
		return *m.DeviceModel
	}
	return ""
}

func (m *LogGameResume) GetAndroidSdk() int32 {
	if m != nil && m.AndroidSdk != nil {
		return *m.AndroidSdk
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "pb.loginRequest")
	proto.RegisterType((*LoginResponse)(nil), "pb.loginResponse")
	proto.RegisterType((*GameServerLoginRequest)(nil), "pb.gameServerLoginRequest")
	proto.RegisterType((*GameServerLoginResponse)(nil), "pb.gameServerLoginResponse")
	proto.RegisterType((*SyncBaseInfoRequest)(nil), "pb.syncBaseInfoRequest")
	proto.RegisterType((*SyncBaseInfoResponse)(nil), "pb.syncBaseInfoResponse")
	proto.RegisterType((*PingRequest)(nil), "pb.pingRequest")
	proto.RegisterType((*PingResponse)(nil), "pb.pingResponse")
	proto.RegisterType((*GetFriendListForStrengthRequesst)(nil), "pb.getFriendListForStrengthRequesst")
	proto.RegisterType((*GetFriendListForStrengthResponse)(nil), "pb.getFriendListForStrengthResponse")
	proto.RegisterType((*SendGameResumeRequest)(nil), "pb.sendGameResumeRequest")
	proto.RegisterType((*SendGameResumeResponse)(nil), "pb.sendGameResumeResponse")
	proto.RegisterType((*LogGameResume)(nil), "pb.LogGameResume")
}

func init() { proto.RegisterFile("client2server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x8a, 0x13, 0x4d,
	0x10, 0x65, 0x26, 0xc9, 0xee, 0xb7, 0x95, 0xec, 0xf2, 0xd9, 0xab, 0x71, 0x10, 0x91, 0x30, 0xa0,
	0x04, 0xc1, 0x5c, 0x2c, 0xa2, 0x77, 0x82, 0x3f, 0xac, 0x04, 0x22, 0xca, 0x64, 0xf1, 0xda, 0xde,
	0xe9, 0xda, 0x49, 0x93, 0x49, 0x77, 0xdb, 0xdd, 0xc9, 0xb2, 0xf7, 0xde, 0xf9, 0x3c, 0xbe, 0x86,
	0xcf, 0x24, 0xd3, 0xf3, 0x93, 0x9e, 0x04, 0x25, 0x37, 0xa1, 0xeb, 0xa4, 0xea, 0x54, 0xd5, 0x99,
	0x43, 0xc1, 0x79, 0x9a, 0x73, 0x14, 0xf6, 0xc2, 0xa0, 0xde, 0xa0, 0x9e, 0x28, 0x2d, 0xad, 0x24,
	0xa1, 0xba, 0x8e, 0x7f, 0x07, 0x30, 0xc8, 0x65, 0xc6, 0x45, 0x82, 0xdf, 0xd7, 0x68, 0x2c, 0x79,
	0x04, 0xff, 0x31, 0xdc, 0xf0, 0x14, 0xa7, 0x2c, 0x0a, 0x46, 0xe1, 0xf8, 0x24, 0x69, 0x62, 0xf2,
	0x1c, 0xfe, 0xb7, 0x0b, 0xae, 0xd9, 0xdb, 0x34, 0x95, 0x6b, 0x61, 0xaf, 0xee, 0x14, 0x46, 0x9d,
	0x51, 0x38, 0xee, 0x25, 0x7b, 0x38, 0x89, 0x61, 0xe0, 0x63, 0x51, 0xd7, 0x71, 0xb5, 0x30, 0x32,
	0x82, 0xbe, 0x8b, 0xbf, 0x50, 0x63, 0x6e, 0x59, 0xd4, 0x73, 0x29, 0x3e, 0x44, 0x86, 0x70, 0xa4,
	0x6e, 0x5c, 0x9f, 0x23, 0xd7, 0xa7, 0x8a, 0x48, 0x04, 0xc7, 0x1b, 0xd4, 0x86, 0x4b, 0x11, 0x1d,
	0xbb, 0xaa, 0x3a, 0x8c, 0x7f, 0x06, 0x70, 0x5a, 0x2d, 0x64, 0x94, 0x14, 0x06, 0xc9, 0x63, 0x38,
	0x41, 0xad, 0xa5, 0x7e, 0x2f, 0x19, 0xba, 0x95, 0x7a, 0xc9, 0x16, 0x20, 0x67, 0x10, 0x72, 0x15,
	0x85, 0x8e, 0x24, 0xe4, 0x8a, 0x10, 0xe8, 0x2a, 0xa9, 0x6d, 0xb5, 0x97, 0x7b, 0x17, 0x9a, 0xd0,
	0xb5, 0x5d, 0x38, 0x82, 0x72, 0x8f, 0x26, 0x2e, 0xd8, 0x69, 0xb9, 0xce, 0xb4, 0xdc, 0xa0, 0x93,
	0x6c, 0x81, 0xf8, 0x47, 0x00, 0xc3, 0x8c, 0xae, 0x70, 0xee, 0x74, 0x9f, 0xf9, 0x42, 0xb7, 0x0a,
	0x83, 0x9d, 0xc2, 0x56, 0xcb, 0x70, 0xa7, 0xe5, 0x56, 0x94, 0xce, 0xdf, 0x44, 0xe9, 0xb6, 0x45,
	0x79, 0x0d, 0x0f, 0xf7, 0xa6, 0x38, 0x44, 0x9d, 0xf8, 0x33, 0x9c, 0x9b, 0x3b, 0x91, 0xbe, 0xa3,
	0x06, 0xa7, 0xe2, 0x46, 0x7a, 0xb3, 0x2f, 0x90, 0xb2, 0xe9, 0x8a, 0x66, 0x4d, 0x51, 0x03, 0x14,
	0xb3, 0x0b, 0x9e, 0x2e, 0x05, 0x5d, 0x35, 0xb3, 0xd7, 0x71, 0xfc, 0x12, 0xee, 0xb7, 0x09, 0x0f,
	0x1a, 0xe3, 0x05, 0xf4, 0x15, 0x17, 0x59, 0xdd, 0xfe, 0x09, 0x40, 0xe9, 0xe7, 0x2b, 0xbe, 0xaa,
	0xb3, 0x3d, 0x24, 0x9e, 0xc1, 0xa0, 0x4c, 0x3f, 0xc8, 0x01, 0x6d, 0xb6, 0x70, 0x8f, 0xed, 0x03,
	0x8c, 0x32, 0xb4, 0x97, 0x9a, 0xa3, 0x60, 0x33, 0x6e, 0xec, 0xa5, 0xd4, 0x73, 0xab, 0x51, 0x64,
	0x76, 0x51, 0x0e, 0x64, 0x9c, 0x93, 0x55, 0x4e, 0x53, 0x5c, 0xc8, 0x9c, 0xa1, 0xae, 0x7a, 0xf8,
	0x50, 0xfc, 0xed, 0x5f, 0x2c, 0x87, 0xce, 0xd9, 0xf8, 0xc3, 0x44, 0xe1, 0xa8, 0x33, 0xee, 0x26,
	0x1e, 0x12, 0xbf, 0x81, 0x07, 0x06, 0x05, 0xfb, 0x48, 0x57, 0x98, 0xa0, 0x59, 0x17, 0xbf, 0xa5,
	0x5c, 0x4f, 0xa1, 0xcb, 0xa8, 0xa5, 0x8e, 0xb1, 0x7f, 0x71, 0x6f, 0xa2, 0xae, 0x27, 0x33, 0x99,
	0x79, 0x79, 0xee, 0xef, 0xf8, 0x15, 0x0c, 0x77, 0xeb, 0x0f, 0xfa, 0x38, 0xbf, 0x02, 0x38, 0x6d,
	0xf1, 0x15, 0x46, 0xcc, 0x65, 0x66, 0xb7, 0x72, 0xd6, 0x21, 0x79, 0x06, 0x67, 0x7a, 0x2d, 0x8a,
	0xe7, 0xd7, 0xca, 0xa9, 0x1d, 0x67, 0x90, 0x1d, 0xb4, 0xd0, 0x53, 0xa0, 0xbd, 0x95, 0x7a, 0xe9,
	0x7c, 0x5e, 0xda, 0xd9, 0x87, 0x8a, 0x8c, 0xf2, 0x2e, 0x7d, 0x92, 0x0c, 0xf3, 0xfa, 0x76, 0x78,
	0x90, 0xd3, 0x4b, 0x30, 0x2d, 0x39, 0x9b, 0xb3, 0x65, 0x75, 0x3f, 0x3c, 0xe4, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc2, 0x13, 0x14, 0x9e, 0x14, 0x05, 0x00, 0x00,
}
